name         'rfletcher-jq'
version      '0.0.1'
license      'MIT License'
summary      'A puppet module for jq'
description  'Install or remove jq'
project_page 'https://github.com/rfletcher/puppet-jq'
dependency   'puppetlabs/apt', '>= 1.4.2'
